version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    volumes:
      - /home/ollama:/root/.ollama:z
    ports:
      - "11434:11434"
    stdin_open: true
    tty: true
